spire-readme.md:
  pull: https://github.com/spiffe/spire/blob/v0.10.0/README.md
  frontMatter:
    title: SPIRE Readme
    short: SPIRE's repo readme
spiffe-governance.md:
  pull: https://github.com/spiffe/spiffe/blob/master/GOVERNANCE.md
  frontMatter:
    title: SPIFFE Governance
    short: Governance specs for SPIFFE
spiffe-sig-spec.md:
  pull: https://github.com/spiffe/spiffe/blob/master/community/sig-spec/README.md
  removeHeading: true
  frontMatter:
    title: SIG-SPEC
    short: SPIFFE's SIG-SPEC readme